apiVersion: v1
kind: Service
metadata:
  name: {{ include "background-agent.fullname" . }}
spec:
  selector:
    app: {{ include "background-agent.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8005
